### ISSUE TITLE
Option to include number in result

### ISSUE THREAD

**Issue by ameykusurkar** [ycmjason/thize#2]
Option to include number in the result. This is so that we can do:
```js
console.log("This is the " + thize(i, true) + " time");
```
instead of:
```js
console.log("This is the " + i + thize(i) + " time");
```

**Comment by ycmjason** [comment]
Like the idea of including the number as well. But not a big fan of random boolean that switches stuff.

Maybe we could export another function that includes the number:

```js
thize.withNumber(i)
```

Not so sure what the method should be called tho, ideas?

**Comment by ycmjason** [comment]
Actually maybe `thize` should include the number by default. And the extra method excludes the number. Coz `th-ize` sounds like it is going to transform `1` into `1st`.

**Comment by ameykusurkar** [comment]
Yup, I like that. Maybe something like:
```js
thize.thize(1); // "1st"
thize.suffix(1); // "st"
```

**Comment by ycmjason** [comment]
Sounds good. We could attach functions to function. So something like

```js
const thize = require('thize');
thize(1); // '1st'
thize.suffix(1); // 'st'
```

**Comment by ameykusurkar** [comment]
Yup that would be ideal!

**Comment by ycmjason** [comment]
💢💢 That means more tests 💢💢

**Comment by ycmjason** [comment]
@ameykusurkar You wanna pick this up? Or I could do this tonight.

**Comment by ameykusurkar** [comment]
Yeah I can do it, but I'll probably do it later today as well.
